[tools]
python = "3.10"

[tasks.install-publish]
run = "poetry install --no-root --without dev,test"

[tasks.publish]
run = """
poetry run python -m build
poetry run twine upload dist/*
"""

[tasks.install-test]
run = "poetry install --no-root --without dev,publish"

[tasks.test]
run = "poetry run pytest -s"
